import { Outfit } from 'next/font/google'
import './globals.css'
import { Toaster as Tostify } from 'sonner';
const outfit = Outfit({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })


export const metadata = {
  title: "HirePath App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body
        className={outfit.className}>
        {children}
        <Tostify  position="top-right" richColors closeButton/>
      </body>
    </html>
  )
}
